### PR TITLE
Folder restructure and linting

### PR DESCRIPTION
**Pull request by dave-ok**
@Balanced02 I restructured the app to use versioning and kept the initial version by @devamaz in v1. Currently working in v2 and hope to continue there. Added linting and prettier for code formatting. Replaced jwt processing with express-jwt and a few edits. Please, let me know your thoughts

### CODE REVIEW

**Comment by devamaz** [comment]
Any reason for replacing jwt with express-jwt

**Comment by dave-ok** [comment]
Have you looked at express-jwt implementation? You will see how simple it is to setup. Initaialize and configure in one place, at the main route. You don't need to apply middleware on separate routes anymore.

P.S @devamaz Where have you been?

**Comment by Balanced02** [comment]
@devamaz @dave-ok , I think the express-jwt is okay, except if @devamaz has any security concern or size issues with it... 

@dave-ok fix merge conflicts at .env.example and package.json. Thanks

**Comment by devamaz** [comment]
Not really. I was just curious. And yeah it looks better

**Review by Balanced02 — APPROVED** [review]

**Review by inidaname — APPROVED** [review]

**Comment by inidaname** [comment]
@devamaz what is your review on the changes, LGTM

**Review by devamaz — APPROVED** [review]

**Comment by devamaz** [comment]
The changes are OK. LGTM

**Pull request merged**
